name: Deploy Frontend Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        # Pass build arguments for frontend environment variables
        # Ensure REACT_APP_BACKEND_URL is passed with the correct prefix
        run: docker build -t zunsod/proshop-frontend --build-arg REACT_APP_NODE_ENV='production' --build-arg REACT_APP_BACKEND_URL=${{ secrets.BACKEND_URL }} .

      - name: Push Docker Image to Docker Hub
        run: docker push zunsod/proshop-frontend:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Log in to Docker Hub (on self-hosted runner)
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull Docker Image from Docker Hub
        run: docker pull zunsod/proshop-frontend:latest

      - name: Stop and Remove Old Container
        # Use || true to prevent failure if container doesn't exist
        run: docker rm -f proshop-frontend-container || true

      - name: Run Docker Container
        # Frontend typically doesn't need MONGO_PASSWORD or other backend secrets.
        # Removed -e MONGO_PASSWORD as it's not relevant for the frontend.
        run: |
          docker run -d \
          -p 3000:80 \
          --name proshop-frontend-container \
          zunsod/proshop-frontend:latest
